# Generated by Django 5.1 on 2024-08-30 19:51

import pandas as pd
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def init_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Property = apps.get_model("api", "Property")

    # Create superuser
    if not User.objects.filter(username=settings.ADMIN_USERNAME):
        user = User(username=settings.ADMIN_USERNAME)
        user.password = make_password(settings.ADMIN_PASSWORD)
        user.is_staff = True
        user.is_superuser = True
        user.save()

    # Load properties
    df = pd.read_excel(
        f"{settings.BASE_DIR}/data/Enodo_Skills_Assessment_Data_File.xlsx"
    )
    property_list = []
    for _, rows in df.iterrows():
        new_property = Property(
            full_address=str(rows["Full Address"]).rstrip(),
            lon=rows["Longitude"],
            lat=rows["Latitude"],
            class_description=str(rows["CLASS_DESCRIPTION"]).rstrip(),
            estimated_market_value=int(rows["ESTIMATED_MARKET_VALUE"]),
            bldg_use=str(rows["BLDG_USE"]).rstrip(),
            building_sq_ft=int(rows["BUILDING_SQ_FT"]),
        )
        property_list.append(new_property)

    Property.objects.bulk_create(property_list)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(init_data, migrations.RunPython.noop),
    ]
